version: "3.8"
services:
  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    environment:
      SENSOR_HOST: sensors
    image: dashboard
    networks:
      - microservices
    ports:
      - 5000:5000

  sensors:
    build:
      context: .
      dockerfile: sensors/Dockerfile
    image: sensors
    networks:
      - microservices
    ports:
      - 50051:50051
      - 50052:50052
      - 50053:50053
networks:
  microservices: